name: just_rain
description: "Just Rain"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.6

flutter:
  uses-material-design: true
  fonts:
    - family: Amatic
      fonts:
        - asset: fonts/AmaticSC-Regular.ttf
